import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react";
import Image from 'next/image'

const sdkKey = process.env.NEXT_PUBLIC_API_KEY;
const projectId = process.env.NEXT_PUBLIC_DEFAULT_PROJECT_ID;

const axios = require('axios');
axios.defaults.headers.common['Authorization'] = sdkKey;

export default function Home() {

  const [flagData, setFlagData] = useState([]);

  useEffect(() => {

    let environmentData = '';

    axios.get(`https://api.optimizely.com/v2/environments?project_id=${projectId}`)
    .then(function (response) {
      environmentData = response.data.map(x => {
        return {
          name: x.name,
          datafile: JSON.stringify(x.datafile)
        };
      });
      setFlagData(environmentData);
    });

  },[]);

  return (
    <>
      <Head>
        <title>Optimizely Demo</title>
        <meta name="description" content="Generated by JonDJones" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div>
          {flagData.map(({ name, datafile }, index) => (
            <div key={index}> {name} <br /> {datafile} </div>
          ))}
        </div>

      </main>

    </>
  )
}
