import Head from 'next/head'

import { fetchEntries } from '../utils/contentfulConnector';
import { v4 as uuidv4 } from 'uuid';
import { useEffect, useState } from "react";
import { useRouter } from 'next/router'
import { createInstance } from "@optimizely/optimizely-sdk";

import ContentRecommendations from '../component/ContentRecommendations'
import VariationContainerRenderer from '../component/VariationContainerRenderer';

const sdkKey = process.env.NEXT_PUBLIC_OPTIMIZELY_SDK_KEY_CONTENTFUL_PROJECT;
const dataFileUrl = `https://cdn.optimizely.com/datafiles/${sdkKey}.json`;

const Home = (props) => {

    let [ variationId, setVariationToUse ] = useState('');

    const { fields, datafile } = props;
    const router = useRouter();

    const optimizelyClient = createInstance({
        datafile: datafile,
    });

    const { id } = router.query
    const userId = id || uuidv4();
    console.log(`userId`, userId);

    useEffect(() => {
        optimizelyClient.onReady().then(() => {
            const variationToUse = optimizelyClient.activate('a_b', userId);
            setVariationToUse(variationToUse);
        });
    }, [optimizelyClient, variationId]);

    return (
        <>
            <Head>
                <title>Optimizely Demo</title>
                <meta name="description" content="Generated by JonDJones" />
                <link rel="icon" href="/favicon.ico" />

            </Head>
            <section id="main">
                <div className="container">
                    <div className="row">

                            <div id="content" className="col-8 col-12-medium imp-medium">
                                {fields.map((item, index) =>
                                    <VariationContainerRenderer
                                            key={index}
                                            item={item}
                                            variationToUse={variationId} />
                                )}
                            </div>

                            <div id="sidebar" className="col-4 col-12-medium">
                                <ContentRecommendations />
                            </div>
                    </div>
                </div>
            </section>
        </>
    )
}

export async function getStaticProps() {

    const response = await fetch(dataFileUrl);
    const datafile = await response.json();

    const entries = await fetchEntries();

    let data = entries.items.filter(() => function() {
    return item.sys.contentType.sys.id === 'page'})
    const fields = data.map((item) => item.fields );

    return {
        props: {
            fields: fields,
            data: data,
            datafile: datafile
        }
    }

}

export default Home;