import Head from 'next/head'
import { useEffect, useState } from "react";
import { v4 as uuidv4 } from 'uuid';
import { createInstance } from "@optimizely/optimizely-sdk";
import { useRouter } from 'next/router'

import ABComponent from "../component/ABComponent";
import FeatureFlagComponent from "../component/FeatureFlagComponent";
import MultiArmBanditComponent from "../component/MultiArmBanditComponent";

const sdkKey = process.env.NEXT_PUBLIC_SDK_KEY;
const dataFileUrl = `https://cdn.optimizely.com/datafiles/${sdkKey}.json`;

export default function Home({...props}) {

  const { datafile, clientId } = props;

  let [ isFeatureEnabled, renderIsFeatureEnabled ] = useState(false);
  let [ backgroundColor, setBackgroundColor ] = useState('');
  let [ componentTitle, setComponentTitle ] = useState('');
  let [ bannerText, setBannerText ] = useState('');
  let [ buttonUrl, setButtonUrl ] = useState('');
  let [ postData, setPostData ] = useState({});

  const router = useRouter()

  const optimizelyClient = createInstance({
    datafile: datafile,
  });

  // Got user Id either via query-string, or, create a random one
  const { id } = router.query
  const userId = id || uuidv4();
  console.log(`user-id`, userId);

  let optimizelyUserContext;

  optimizelyClient.onReady().then(() => {
    optimizelyUserContext = optimizelyClient.createUserContext(
      userId,
      {
        location: "london",
        deviceType: "ios"
      }
    );
  });

  useEffect(() => {

    optimizelyClient.onReady().then(() => {

      // Feature flag code
      const featureFlag = optimizelyUserContext.decide('feature_flag');
      console.log('featureFlag', featureFlag);
      renderIsFeatureEnabled(featureFlag.enabled);

      // AB Testing Code
      const abTestFlag = optimizelyUserContext.decide('ab_test');
      console.log('abTest', abTestFlag);
      setBackgroundColor(abTestFlag.variables.backgroundcolour);
      setComponentTitle(abTestFlag.variables.component_title);
      setBannerText(abTestFlag.variables.button_text);
      setButtonUrl(abTestFlag.variables.button_url);

      /// Multi-arm bandit code
      const apiDataJson = optimizelyClient.getFeatureVariable('multi-arm_bandit', 'api_data', userId);
      const apiUrl = apiDataJson?.url;

      const fetchData = async () => {
        const response = await fetch(apiUrl);
        const json = await response.json();
        setPostData(json);
      }
      fetchData().catch(console.error);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Optimizely Demo</title>
        <meta name="description" content="Generated by JonDJones" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="features">
        <div className="container" id="feature-container">
          <header>
            <h2>
              <strong>
                  {"Feature Flag Example: " + isFeatureEnabled}
              </strong>
            </h2>
          </header>

          {isFeatureEnabled &&
            <FeatureFlagComponent userId={userId}
                                  optimizelyClient={optimizelyClient}
                                  clientId={clientId} />
          }
        </div>
      </section>

      <section id="main">

          {componentTitle &&
            <ABComponent  key={`${componentTitle}${backgroundColor}`}
                          userId={userId}
                          optimizelyClient={optimizelyClient}
                          backgroundColor={backgroundColor}
                          componentTitle={componentTitle}
                          bannerText={bannerText}
                          buttonUrl={buttonUrl} />
          }

        <MultiArmBanditComponent  key={postData.id}
                                  userId={userId}
                                  optimizelyClient={optimizelyClient}
                                  clientId={clientId}
                                  postId={postData.id}
                                  title={postData.title} />
      </section>
    </>
  )
}

export async function getServerSideProps() {
  const response = await fetch(dataFileUrl);
  const datafile = await response.json();

  return {
    props: {
      datafile
    }
  }
}