import Head from 'next/head'
import React, { useEffect, useState } from "react";
import { v4 as uuidv4 } from 'uuid';

import { useRouter } from 'next/router'

import ABComponent from "../component/ABComponent";
import FeatureFlagComponent from "../component/FeatureFlagComponent";

import {
  createInstance
} from "@optimizely/optimizely-sdk";

const sdkKey = process.env.NEXT_PUBLIC_SDK_KEY;
const dataFileUrl = `https://cdn.optimizely.com/datafiles/${sdkKey}.json`;

export default function Home({...props}) {

  const [ isFeatureEnabled, renderIsFeatureEnabled ] = useState(true);
  const [ backgroundColor, setBackgroundColor ] = useState('');
  const [ componentTitle, setComponentTitle ] = useState('');
  const [ postData, setPostData ] = useState({});

  const router = useRouter()

  const optimizelyClient = createInstance({

    datafile: props?.datafile,
  });

  // Got user Id either via query-string, or, create a random one
  const { id, location } = router.query
  const userId = id || uuidv4();

  let optimizelyUserContext;

  optimizelyClient.onReady().then(() => {
    optimizelyUserContext = optimizelyClient.createUserContext(
      userId,
      {
        location: location || "london",
        deviceType: "ios"
      }
    );
  });

  useEffect(() => {

    optimizelyClient.onReady().then(() => {

      // Feature flag code
      const featureFlag = optimizelyUserContext.decide('feature_flag');
      console.log('featureFlag', featureFlag.enabled);
      renderIsFeatureEnabled(featureFlag.enabled);

      // AB Testing Code
      const abTestData = optimizelyUserContext.decide('ab_test');
      setBackgroundColor(abTestData.variables.backgroundcolour);
      setComponentTitle(abTestData.variables.component_title);

      /// Multi-arm bandit code
      const apiDataJson = optimizelyClient.getFeatureVariable('multi-arm_bandit', 'api_data', userId);
      const apiUrl = apiDataJson.url;

      const fetchData = async () => {
        const response = await fetch(apiUrl);
        const json = await response.json();

        console.log('API Call', apiUrl, json);
        setPostData(json);
      }

      fetchData().catch(console.error);
    });
  }, [optimizelyUserContext]);

  const bannerClicked = (id) => {
    optimizelyClient.track('banner_click', userId, {variation: id});
    console.log(`Banner ${id} clicked`)
  }

  return (
    <>
      <Head>

        <title>
          Optimizely Fullstack Javascript
        </title>

        <meta name="description" content="Generated by JonDJones" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="features">
        <div className="container" id="feature-container">
          <header>
            <h2>
              <strong>
                  {"Feature Flag Example: " + isFeatureEnabled}
              </strong>
            </h2>
          </header>
        </div>
      </section>

      {isFeatureEnabled &&
        <FeatureFlagComponent userId={userId} optimizelyClient />
      }

      <section id="main">
        <div className="container">
          <header>
            <h2>
              <strong>
              {"AB Test Example"}
              </strong>
            </h2>
          </header>

          <ABComponent userId={userId} optimizelyClient backgroundColor={backgroundColor} componentTitle={componentTitle} />

        </div>
        <div className="container">
              <header>
                <h2>
                  <strong>
                  {"Multi-arm Bandit Example: " + postData.id}
                  </strong>
                </h2>
              </header>

              <a href="#" className="image featured" onClick={bannerClicked(postData.id)}>
                <img src={`./images/${postData.id}.png`} alt={postData.title} />
              </a>
        </div>
      </section>
    </>
  )
}

export async function getServerSideProps(context) {
  const response = await fetch(dataFileUrl);
  const datafile = await response.json();

  return {
    props: {
      datafile
    }
  }
}