import Head from 'next/head'
import React, { useEffect, useState } from "react";
import { v4 as uuidv4 } from 'uuid';

import { useRouter } from 'next/router'

import {
    createInstance
} from "@optimizely/optimizely-sdk";

const sdkKey = process.env.NEXT_PUBLIC_SDK_KEY;
const dataFileUrl = `https://cdn.optimizely.com/datafiles/${sdkKey}.json`;

export default function Landing({...props}) {

  const [ displayBanner, renderPersonalisationBanner ] = useState(false);

  const router = useRouter()

  const optimizelyClient = createInstance({
    datafile: props?.datafile,
  });

  const { user = '' } = router.query
  const userId = uuidv4();

  let optimizelyUserContext;

  console.log('user segment', user);

  optimizelyClient.onReady().then(() => {
    optimizelyUserContext = optimizelyClient.createUserContext(
      userId,
      {
        user: user
      }
    );
  });

    useEffect(() => {
        optimizelyClient.onReady().then(() => {

        const decision  = optimizelyUserContext.decide('personalisation');
        console.log('matched on key', decision.ruleKey, decision);

        renderPersonalisationBanner(decision.enabled);
        });
    }, [optimizelyUserContext, optimizelyClient]);

  return (
    <>
      <Head>

        <title>
          Optimizely Fullstack Javascript
        </title>

        <meta name="description" content="Generated by JonDJones" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="features">
        <div className="container" id="feature-container">
          <header>
            <h2>
              <strong>
                  {"Display Personlisation: " + displayBanner}
              </strong>
            </h2>
          </header>
        </div>
      </section>

      {displayBanner ?
        <section id="main">
          <div className="container">
            <header>
              <h2>
                <strong>
                  Hello VIP User!
                </strong>
              </h2>
            </header>
          </div>
        </section> : null
      }
    </>
  )
}

export async function getServerSideProps(context) {
  const response = await fetch(dataFileUrl);
  const datafile = await response.json();

  return {
    props: {
      datafile
    }
  }
}