import Head from 'next/head'
import React, { useEffect, useState } from "react";
import { v4 as uuidv4 } from 'uuid';
import { useRouter } from 'next/router'
import Link from "next/link";
import DiscountBanner from "../component/DiscountBanner";

import {
    createInstance
} from "@optimizely/optimizely-sdk";

const sdkKey = process.env.NEXT_PUBLIC_SDK_KEY;
const dataFileUrl = `https://cdn.optimizely.com/datafiles/${sdkKey}.json`;

export default function Landing({...props}) {

  const { datafile, clientId} = props;

  const [ componentMessage, setComponentMessage ] = useState();
  const [ discountAmount, setDiscountAmount ] = useState();

  const router = useRouter()

  const optimizelyClient = createInstance({
    datafile: datafile,
  });

  const { segment = '' } = router.query
  const userId = uuidv4();

  console.log(segment)

  let optimizelyUserContext;

  optimizelyClient.onReady().then(() => {
    optimizelyUserContext = optimizelyClient.createUserContext(
      userId,
      {
        segment: segment,
        user: segment
      }
    );
  });

  useEffect(() => {
      optimizelyClient.onReady().then(() => {

        const decision  = optimizelyUserContext.decide('personalisation');
        console.log('personalisation-flag', decision);

        const componentMessage = decision.variables.component_message;
        const discountAmount = decision.variables.discount_amount;

        if (discountAmount && discountAmount >= 0) {
          setDiscountAmount(discountAmount);
        }

        setComponentMessage(componentMessage);
      });
  }, [optimizelyUserContext, optimizelyClient]);

  console.log(discountAmount)
  return (
    <>
      <Head>
        <title>Optimizely Demo</title>
        <meta name="description" content="Generated by JonDJones" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DiscountBanner discount={discountAmount} componentMessage={componentMessage} />

      <section id="feaure">
        <div className="container">
						<div className="row aln-center">
							<div className="col-4 col-6-medium col-12-small">
									<section>
										<a href="#" className="image featured">
                      <img src={`images/${clientId}/item.png`} alt="Item 1" />
                    </a>
										<p><img src={`images/landing1.png`} alt="Item 1" /></p>
									</section>

							</div>
							<div className="col-4 col-6-medium col-12-small">

									<section>
										<a href="#" className="image featured">
                      <img src={`images/${clientId}/item.png`} alt="Item 2" />
                    </a>
                    <p><img src={`images/landing2.png`} alt="Item 2" /></p>
									</section>

							</div>
							<div className="col-4 col-6-medium col-12-small">
									<section>
										<a href="#" className="image featured">
                      <img src={`images/${clientId}/item.png`} alt="Item 3" />
                    </a>
                    <p><img src={`images/landing3.png`} alt="Item 3" /></p>
                  </section>
							</div>
						</div>
					</div>
          </section>

        <div className="bottomnav">
              <Link href="/landing?segment=vip">
                  <a>
                    VIP
                  </a>
              </Link> | &nbsp;
              <Link href="/landing?segment=premier">
                  <a>
                  Premier
                  </a>
              </Link> | &nbsp;
              <Link href="/landing?segment=new">
                  <a>
                  New
                  </a>
              </Link>
        </div>
    </>
  )
}

export async function getServerSideProps(context) {
  const response = await fetch(dataFileUrl);
  const datafile = await response.json();

  return {
    props: {
      datafile
    }
  }
}